services:
  postgres-oltp:
    image: postgres:16
    container_name: fraud-oltp-postgres
    command:
      [
        "postgres",
        "-c",
        "wal_level=logical",
        "-c",
        "max_replication_slots=4",
        "-c",
        "max_wal_senders=4",
      ]
    environment:
      POSTGRES_DB: fraud_bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fraud_bank"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_oltp_data:/var/lib/postgresql/data
      - ./postgres/oltp/init:/docker-entrypoint-initdb.d:ro

volumes:
  postgres_oltp_data: