services:
  spark-bronze-stream:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-batch-processing
    entrypoint: ["/opt/spark/bin/spark-submit", "/opt/bronze/cdc_transactions_to_bronze.py"]
    volumes:
      - ./bronze:/opt/bronze:ro
    depends_on:
      kafka:
        condition: service_healthy
      connector-init-debezium:
        condition: service_completed_successfully
    restart: on-failure

  spark-gold-customer-batch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-gold-customer-batch
    entrypoint:
      - /opt/spark/bin/spark-submit
      - /opt/gold/silver_transactions_window_aggregate_customer_gold.py
    volumes:
      - ./gold:/opt/gold:ro
    depends_on:
      spark-silver-batch:
        condition: service_completed_successfully
    restart: on-failure

  spark-bronze-fraud-cases-stream:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-bronze-fraud-cases-stream
    entrypoint: ["/opt/spark/bin/spark-submit", "/opt/bronze/cdc_fraud_cases_to_bronze.py"]
    volumes:
      - ./bronze:/opt/bronze:ro
    depends_on:
      kafka:
        condition: service_healthy
      connector-init-debezium:
        condition: service_completed_successfully
    restart: on-failure

  spark-silver-fraud-cases-batch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-silver-fraud-cases-batch
    entrypoint:
      - /opt/spark/bin/spark-submit
      - /opt/silver/cdc_fraud_cases_normalize_merge_silver.py
    volumes:
      - ./silver:/opt/silver:ro
    depends_on:
      spark-bronze-fraud-cases-stream:
        condition: service_started
    restart: on-failure

  spark-gold-terminal-batch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-gold-terminal-batch
    entrypoint:
      - /opt/spark/bin/spark-submit
      - /opt/gold/silver_transactions_window_aggregate_terminal_gold.py
    volumes:
      - ./gold:/opt/gold:ro
    depends_on:
      spark-silver-batch:
        condition: service_completed_successfully
      spark-silver-fraud-cases-batch:
        condition: service_completed_successfully
    restart: on-failure

  spark-silver-batch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-silver-batch
    entrypoint:
      - /opt/spark/bin/spark-submit
      - /opt/silver/cdc_transactions_normalize_merge_silver.py
    volumes:
      - ./silver:/opt/silver:ro
    depends_on:
      spark-bronze-stream:
        condition: service_started
    restart: on-failure
