name: fraud_detection
version: '1.0.0'
config-version: 2

profile: fraud_detection

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  fraud_detection:
    staging:
      +database: lakehouse
      +schema: staging
      +materialized: incremental
    intermediate:
      +database: clickhouse
      +schema: intermediate
      +materialized: table
    marts:
      +database: clickhouse
      +schema: marts
      +materialized: table
